### PR TITLE
Support functionally perfect via master league PvP

### PR DESCRIPTION
**Pull request by Mygod**
Sample of functionally perfect (15/15/14) Carvanha:

```json
{
 "little":[{"pokemon":318,"form":734,"cap":40,"value":237671,"level":17,"cp":494,"percentage":0.94527,"rank":695,"capped":true}],
 "master":[{"pokemon":318,"form":734,"level":51,"rank":1,"percentage":1}],
 "great":[{"pokemon":319,"form":737,"cap":40,"value":1310282,"level":24,"cp":1491,"percentage":0.95961,"rank":759,"capped":true},{"pokemon":319,"form":737,"cap":40,"value":1366358,"level":16,"cp":1492,"percentage":0.97045,"rank":418,"evolution":1,"capped":true}],
 "ultra":[{"pokemon":319,"form":737,"cap":40,"value":2903042,"level":26.5,"cp":2472,"percentage":0.95453,"rank":1931,"evolution":1,"capped":true}]
}
```

### CODE REVIEW

**Review by TurtIeSocks — CHANGES_REQUESTED** [review]
Why are you adding additional cpu cycles for useless data?

**Comment by Mygod** [comment]
The overhead of this is 100x smaller than little cup. Why don't you read the code?

**Comment by Mygod** [comment]
@TurtIeSocks proposed that it is better to implement this in front end since the computation is much cheaper.

**Comment by versx** [comment]
@TurtIeSocks 💪

**Pull request closed without merging**
